version: '3.8'
services:
    frontend:
        container_name: validatorserviceclient
        build:
            context: ./web/client
            dockerfile: Dockerfile
        image: validatorserviceclient
        ports:
            - "3000:3000"
        volumes:
            - ./client:/app
    backend:
        container_name: validatorservice
        build:
            context: ./validator-service
            dockerfile: Dockerfile
        image: server
        ports:
            - "8000:8000"
        volumes:
            - ./server:/app